# src/common/interfaces.py
from __future__ import annotations
from typing import Any, Dict, List, Optional, Protocol

class BaseLogger(Protocol):
    def event(self, *, qid:str, stage:str, decision:Optional[str]=None,
              score:Optional[float]=None, payload:Optional[Dict[str,Any]]=None,
              latency_ms:Optional[float]=None, **kwargs: Any) -> None: ...
    def start(self, qid:str) -> None: ...
    def end(self, qid:str) -> None: ...

class InputLCE(Protocol):
    def predict(self, x: Dict[str, Any]) -> Dict[str, Any]: ...

class OutputLCE(Protocol):
    def predict(self, text: str) -> Dict[str, Any]: ...

class CoTController(Protocol):
    def run(self, prompt: str, context_html: Optional[str]=None) -> Dict[str, Any]: ...
    def rollback_or_patch(self, call: Dict[str, Any], verifier_result: Dict[str, Any]) -> Dict[str, Any]: ...

class ToolVerifier(Protocol):
    def check(self, call: Dict[str, Any], user_ctx: Dict[str, Any]) -> Dict[str, Any]: ...

class IntentParser(Protocol):
    def parse(self, text: str) -> Dict[str, Any]: ...

class ConfigProvider(Protocol):
    def get(self, path: str, default: Any=None) -> Any: ...
